/*
 * Founder Review Demo only. No fetch/XHR, no API client and no credentials.
 * State is intentionally limited to the current browser's localStorage.
 */
(function () {
  'use strict';

  const STORE = 'essence-founder-review-demo-v1';
  const now = '03/08/2026, 10:20';
  const initial = {
    view: 'overview',
    langStatus: 'Chờ Kenji quyết định',
    langDecision: null,
    payment: 'Đã báo chuyển khoản — chờ review',
    hatmamStatus: 'Đã thanh toán',
    publication: 'Chờ Kenji duyệt',
    deletion: 'Mở — chưa thực thi',
    leads: 24,
    ebook: { name: 'Ebook mẫu — chờ nội dung duyệt', status: 'Tạm dừng', route: 'Chưa có reading route thật', delivery: 'Email giao ebook v0 — dữ liệu giả' },
    assessment: { stage: 'Chưa bắt đầu', paid: false, result: null, sequence: 'Chưa bắt đầu' },
    settings: { price: 2000000, capacity: 10, delivery: 5, revision: 7, retention: 12 },
    versions: [{ number: 3, time: '02/08/2026, 16:10', label: 'Phiên bản đang dùng', price: 2000000, capacity: 10 }],
    wizard: { start: null, step: 1, saved: false },
    library: { item: 'assessment-01', chapter: 1, supportRequests: 0, revisionApplied: false },
    assistantOpen: false,
    audit: [
      { time: '03/08/2026, 09:20', text: 'Hồ sơ Lặng giả L-024 được đưa vào hàng chờ Kenji.' },
      { time: '03/08/2026, 09:35', text: 'Biên nhận giả cho HM-018 đã được báo; cần Kenji review.' },
      { time: '02/08/2026, 16:10', text: 'Cài đặt phiên bản 3 được kích hoạt trong dữ liệu demo.' }
    ]
  };
  const nav = [
    ['overview', 'Tổng quan'], ['growth', 'Khách hàng'], ['work', 'Công việc'],
    ['catalog', 'Cấu hình kinh doanh'], ['system', 'Hệ thống']
  ];
  const main = document.getElementById('main');
  const navigation = document.getElementById('navigation');
  const toast = document.getElementById('toast');
  const assistantPanel = document.getElementById('assistant-panel');
  const searchInput = document.getElementById('demo-search');
  const searchResults = document.getElementById('search-results');
  let timer;

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function state() {
    try { const saved = JSON.parse(localStorage.getItem(STORE)); return saved ? { ...clone(initial), ...saved } : clone(initial); }
    catch (_) { return clone(initial); }
  }
  let data = state();
  function save() { localStorage.setItem(STORE, JSON.stringify(data)); }
  function esc(value) { return String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;', "'":'&#039;' }[c])); }
  function badge(label, tone) { return `<span class="badge ${tone || ''}">${esc(label)}</span>`; }
  function action(label, id, tone) { return `<button class="button ${tone || 'button-secondary'}" data-action="${id}">${label}</button>`; }
  function notice(message) { toast.textContent = message; toast.classList.add('visible'); clearTimeout(timer); timer = setTimeout(() => toast.classList.remove('visible'), 3800); }
  function audit(text) { data.audit.unshift({ time: now, text }); save(); }
  function stat(label, value) { return `<article class="card"><div class="stat-label">${label}</div><div class="stat-value">${value}</div></article>`; }
  function page(title, lede, body) { return `<p class="small">Founder Operating Console · ${esc(title)}</p><h1 class="view-title">${title}</h1><p class="lede">${lede}</p>${body}`; }
  function link(label, view) { return `<button class="link-button" data-view="${view}">${label} →</button>`; }
  function statusTone(status) { return /chặn|quá hạn|OFF|chưa|cần chỉnh|mở/i.test(status) ? 'blocked' : /sẵn sàng|đã thanh toán|phù hợp|duyệt/i.test(status) ? 'ready' : 'pending'; }

  function renderOverview() {
    return page('Tổng quan hôm nay', 'Bắt đầu bằng những việc Kenji cần xử lý — toàn bộ con số và hồ sơ dưới đây là dữ liệu giả.', `
      <div class="notice"><strong>Tóm tắt hỗ trợ theo quy tắc — dữ liệu thử.</strong> Không có AI report thật, không có kết nối dữ liệu vận hành.</div>
      <section class="grid two" style="margin-top:14px">
        <article class="card urgent"><h2>Việc cần Kenji xử lý</h2><div class="action-list">
          <div class="action-row"><div><strong>Đọc và quyết định · L-024</strong><p>${esc(data.langStatus)} · đã chờ 1 giờ 20 phút · hạn xử lý: quá 20 phút</p></div>${link('Mở hồ sơ', 'lang-detail')}</div>
          <div class="action-row"><div><strong>Kiểm tra biên nhận · HM-018</strong><p>${esc(data.payment)} · đã chờ 45 phút · hạn xử lý: trong 15 phút</p></div>${link('Kiểm tra biên nhận', 'payments')}</div>
          <div class="action-row"><div><strong>Duyệt bản thảo · HM-013</strong><p>${esc(data.publication)} · chờ từ hôm qua · hạn giao: 05/08/2026</p></div>${link('Mở ấn phẩm', 'publication')}</div>
        </div></article>
        <article class="card"><h2>Hạn và sức chứa</h2><div class="action-list">
          <div class="action-row"><div><strong>HM-011 quá hạn 1 ngày</strong><p>Target giao: 02/08/2026 · cần xử lý trước</p></div>${badge('QUÁ HẠN','blocked')}</div>
          <div class="action-row"><div><strong>Hạt Mầm tháng 08</strong><p>6/10 chỗ đã dùng · 4 chỗ còn lại</p></div>${badge('CÒN 4 CHỖ','ready')}</div>
          <div class="action-row"><div><strong>Hồ sơ Lặng</strong><p>9/10 suất tháng này · 1 suất còn lại</p></div>${badge('SẮP ĐẦY','pending')}</div>
        </div></article>
      </section>
      <section class="grid stats" style="margin-top:14px">
        ${stat('Hồ sơ Lặng mới', '2')}${stat('Chờ quyết định', data.langDecision ? '1' : '2')}${stat('Thanh toán chờ xác nhận', data.payment.toLowerCase().includes('xác nhận') ? '0' : '1')}${stat('Hạt Mầm đang sản xuất', data.hatmamStatus === 'Đang sản xuất' ? '2' : '1')}
        ${stat('Bản thảo chờ duyệt', data.publication === 'Chờ Kenji duyệt' ? '1' : '0')}${stat('Chỉnh sửa chờ xử lý', data.hatmamStatus === 'Cần chỉnh sửa' ? '1' : '0')}${stat('Yêu cầu xóa', data.deletion.includes('Mở') ? '1' : '0')}${stat('Việc quá SLA', '1')}
      </section>
      <section class="grid two" style="margin-top:14px">
        <article class="card"><h2>Mức sẵn sàng cần biết</h2><div class="readiness">
          <div class="readiness-row"><span>Cal.com</span>${badge('CHƯA KẾT NỐI','blocked')}</div><div class="readiness-row"><span>Resend</span>${badge('CHƯA KẾT NỐI','blocked')}</div><div class="readiness-row"><span>Lưu trữ riêng</span>${badge('CHƯA SẴN SÀNG','blocked')}</div><div class="readiness-row"><span>Kích hoạt công khai</span>${badge('OFF','blocked')}</div>
        </div></article>
        <article class="card"><h2>Tình trạng hệ thống</h2><div class="readiness"><div class="readiness-row"><span>Phiên bản demo</span>${badge('v1.1 · dữ liệu giả','ready')}</div><div class="readiness-row"><span>Deployment gần nhất</span>${badge('Preview branch','ready')}</div><div class="readiness-row"><span>Database / AI</span>${badge('KHÔNG KẾT NỐI','blocked')}</div><div class="readiness-row"><span>Backup</span>${badge('CHỈ MINH HỌA','pending')}</div></div><div class="button-set">${action('Xem trải nghiệm khách hàng','go-customer-home')} ${action('Xem Thư viện khách hàng','go-library')} ${action('Xem hệ thống','go-system')} ${action('Hỏi Trợ lý','ask-assistant')}</div></article>
      </section><section class="card" style="margin-top:14px"><p class="section-label">FOUNDER REVIEW ENTRY POINTS</p><h2>Website, Customer Experience và Launch Core</h2><p class="small">Góc đọc công khai là free/public fixture; Không gian của tôi là paid entitlement fixture. Không entry nào tạo route, account hay provider thật.</p><div class="button-set">${action('1 · Founder Operating Console','go-overview')} ${action('2 · Góc đọc công khai','go-public-reading')} ${action('3 · Không gian của tôi','go-customer-home')} ${action('4 · Cấu hình trải nghiệm','go-cx-config')} ${action('5 · Launch Core map','go-launch-core')}</div></section>`);
  }

  function renderLang() {
    return page('Lặng', 'Hàng chờ hồ sơ giả. Không có tên, email hoặc dữ liệu người thật.', `
      <div class="table-wrap"><table class="table"><thead><tr><th>Mã hồ sơ</th><th>Trạng thái</th><th>Nhận lúc</th><th>SLA</th><th></th></tr></thead><tbody>
      <tr><td><strong>L-024</strong><br><span class="small">Hồ sơ synthetic</span></td><td>${badge(data.langStatus,statusTone(data.langStatus))}</td><td>03/08, 08:40</td><td>${badge('QUÁ 20 PHÚT','blocked')}</td><td>${link('Mở','lang-detail')}</td></tr>
      <tr><td><strong>L-023</strong><br><span class="small">Hồ sơ synthetic</span></td><td>${badge('Đang đọc','pending')}</td><td>03/08, 09:45</td><td>${badge('CÒN 45 PHÚT','ready')}</td><td>${link('Mở','lang-detail')}</td></tr>
      <tr><td><strong>L-021</strong><br><span class="small">Hồ sơ synthetic</span></td><td>${badge('Đã xếp lịch giả','ready')}</td><td>02/08, 14:10</td><td>—</td><td>${link('Mở','lang-detail')}</td></tr>
      </tbody></table></div>
      <div class="notice" style="margin-top:18px">Tất cả hồ sơ trong đây là fixture. Luồng Lặng thật vẫn được bảo vệ bởi Auth, AAL2, RLS và staging gates.</div>`);
  }

  function renderLangDetail() {
    const decision = data.langDecision ? `Quyết định demo: ${data.langDecision}` : 'Chưa có quyết định';
    return page('Hồ sơ Lặng · L-024', 'Hồ sơ minh họa tối thiểu, không có dữ liệu cá nhân hay nội dung của khách.', `
      <div class="detail-head"><div><p class="section-label">SYNTHETIC INTAKE</p><h2 style="margin:0;font-family:Georgia,serif;font-weight:400">L-024 · hồ sơ mẫu</h2><p>${esc(decision)}</p></div>${badge(data.langStatus,statusTone(data.langStatus))}</div>
      <section class="grid two"><article class="card"><h2>Thông tin an toàn để review</h2><div class="kv"><div class="muted">Mục tiêu buổi</div><div>Khám phá một chủ đề chung</div><div class="muted">Khung thời gian</div><div>Buổi 60 phút · synthetic</div><div class="muted">Tóm tắt</div><div>Tóm tắt hỗ trợ theo quy tắc — dữ liệu thử</div><div class="muted">Capacity</div><div>1/10 suất còn lại</div></div></article>
      <article class="card"><h2>Đưa ra quyết định</h2><p class="small">Chỉ thử giao diện. Quyết định này không ghi vào database và không gửi email.</p><div class="button-set">${action('Bắt đầu đọc','lang-read')} ${action('Phù hợp','lang-fit')} ${action('Chờ thêm','lang-more')} ${action('Chưa phù hợp','lang-no')}</div></article></section>
      <section class="grid two" style="margin-top:14px"><article class="card"><h2>Thanh toán và lịch</h2><p>${badge('BIÊN NHẬN GIẢ','pending')} <span class="small">Payment chỉ sau submission hợp lệ.</span></p><div class="button-set">${action('Xem biên nhận giả','go-payment')} ${action('Phát link đặt lịch giả','fake-booking')}</div><p class="small">Cal.com chưa kết nối — không có booking thật được tạo.</p></article><article class="card"><h2>Audit synthetic</h2><ul class="timeline"><li><time>03/08/2026, 08:40</time>Hồ sơ fixture được tạo cho demo.</li><li><time>03/08/2026, 09:20</time>Được đưa vào hàng chờ Kenji.</li>${data.langDecision ? `<li><time>${now}</time>Đã chọn “${esc(data.langDecision)}” trong browser.</li>` : ''}</ul></article></section>`);
  }

  function renderPayments() {
    return page('Thanh toán', 'Kiểm tra biên nhận demo — biên nhận giả chỉ gắn với đúng đơn giả HM-018.', `
      <div class="notice"><strong>Điều kiện xác nhận thanh toán (minh họa):</strong> chỉ khi đúng đơn, thời điểm báo chuyển, bằng chứng, request chưa thu hồi, số tiền và mã chuyển khoản khớp package snapshot thì nút xác nhận mới hiển thị.</div>
      <section class="grid two"><article class="card"><h2>Biên nhận giả · HM-018</h2><div class="kv"><div class="muted">Package snapshot</div><div>HM-01 · Ấn phẩm Bản Sắc — phiên bản 3</div><div class="muted">Amount snapshot</div><div>₫2.000.000</div><div class="muted">Transfer reference</div><div>DEMO-HM-018</div><div class="muted">Evidence synthetic</div><div>${badge('ĐÃ ĐÍNH KÈM','ready')}</div><div class="muted">Reported transfer</div><div>03/08/2026, 09:35</div></div><div class="button-set">${action(data.payment.toLowerCase().includes('xác nhận') ? 'Đã xác nhận' : 'Xác nhận payment giả','confirm-payment', data.payment.toLowerCase().includes('xác nhận') ? 'button-quiet' : '')}</div></article>
      <article class="card"><h2>Kiểm tra atomically</h2><div class="readiness"><div class="readiness-row"><span>Đúng subject / order</span>${badge('PASS','ready')}</div><div class="readiness-row"><span>Evidence + reported time</span>${badge('PASS','ready')}</div><div class="readiness-row"><span>Request chưa revoked</span>${badge('PASS','ready')}</div><div class="readiness-row"><span>Amount + reference khớp snapshot</span>${badge('PASS','ready')}</div></div><p class="small">Đây là bằng chứng mô phỏng; không tạo receipt hay payment thật.</p></article></section>
      <section class="card" style="margin-top:14px"><h2>Không có receipt dùng chung</h2><p class="small">HM-017 bị chặn trong fixture vì reference không khớp. Giao diện không cho xác nhận dựa chỉ vào trạng thái “awaiting payment”.</p>${badge('BỊ CHẶN — REFERENCE KHÔNG KHỚP','blocked')}</section>`);
  }

  function renderHatmam() {
    return page('Hạt Mầm', 'Danh sách đơn dữ liệu giả. Giá và thời hạn của từng đơn được bảo toàn từ package snapshot.', `
      <div class="table-wrap"><table class="table"><thead><tr><th>Mã đơn</th><th>Trạng thái</th><th>Giao trước</th><th>Chỉnh sửa đến</th><th></th></tr></thead><tbody>
        <tr><td><strong>HM-018</strong><br><span class="small">HM-01 · Snapshot v3 · ₫2.000.000</span></td><td>${badge(data.hatmamStatus,statusTone(data.hatmamStatus))}</td><td>08/08/2026</td><td>15/08/2026</td><td>${link('Mở đơn','hatmam-detail')}</td></tr>
        <tr><td><strong>HM-013</strong><br><span class="small">HM-02 · Snapshot v2 · ₫3.500.000</span></td><td>${badge(data.publication,'pending')}</td><td>05/08/2026</td><td>12/08/2026</td><td>${link('Review','publication')}</td></tr>
        <tr><td><strong>HM-011</strong><br><span class="small">HM-01 · Snapshot v2 · ₫2.000.000</span></td><td>${badge('Đang sản xuất','pending')}</td><td>02/08/2026</td><td>09/08/2026</td><td>${badge('QUÁ HẠN','blocked')}</td></tr>
      </tbody></table></div>
      <div class="callout" style="margin-top:16px">Monthly capacity: <strong>6/10</strong>. Thay đổi cài đặt demo có thể tác động đơn mới, nhưng không đổi price, package, delivery, revision hay retention của HM-013/HM-018 đã snapshot.</div>`);
  }

  function renderHatmamDetail() {
    return page('Đơn Hạt Mầm · HM-018', 'Một đơn giả để Founder thử toàn bộ state transition theo thứ tự.', `
      <div class="detail-head"><div><p class="section-label">SYNTHETIC ORDER · PACKAGE SNAPSHOT V3</p><h2 style="margin:0;font-family:Georgia,serif;font-weight:400">HM-018 · Hạt Mầm</h2><p>Giao trước 08/08/2026 · cửa sổ revision đến 15/08/2026</p></div>${badge(data.hatmamStatus,statusTone(data.hatmamStatus))}</div>
      <section class="grid two"><article class="card"><h2>State truth</h2><div class="kv"><div class="muted">Payment</div><div>${esc(data.payment)}</div><div class="muted">Sản xuất</div><div>${esc(data.hatmamStatus)}</div><div class="muted">Delivery</div><div>${data.hatmamStatus === 'Sẵn sàng' ? 'Bị B4 chặn — Private Storage OFF' : 'Chưa đến bước giao'}</div><div class="muted">Revision deadline</div><div>15/08/2026</div></div></article>
      <article class="card"><h2>Thao tác workflow giả</h2><p class="small">Các nút chỉ chạy trong browser; trạng thái phải đi theo trình tự.</p><div class="button-set">${action('Mở payment','go-payment')} ${action('Bắt đầu sản xuất','start-production')} ${action('Chờ Kenji duyệt','queue-review')} ${action('Yêu cầu chỉnh sửa','request-revision')} ${action('Duyệt lại','approve-revision')} ${action('Đánh dấu sẵn sàng','mark-ready')}</div></article></section>
      <section class="card" style="margin-top:14px"><h2>Snapshot integrity</h2><div class="kv"><div class="muted">Tên package đã snapshot</div><div>HM-01 · Ấn phẩm Bản Sắc</div><div class="muted">Giá đã snapshot</div><div>₫2.000.000</div><div class="muted">Delivery snapshot</div><div>5 business days</div><div class="muted">Retention snapshot</div><div>Raw intake 12 tháng · private room 24 tháng</div></div></section>`);
  }

  function renderProduction() {
    return page('Quy trình sản xuất', 'Một bản đồ thao tác để thấy thứ tự công việc, deadline và gate trước khi giao.', `<section class="card"><div class="production-step"><span class="step-number">1</span><div><strong>Payment evidence review</strong><p>Kenji kiểm tra đúng receipt giả với snapshot, reference và reported time.</p></div></div><div class="production-step"><span class="step-number">2</span><div><strong>Đang sản xuất</strong><p>Target: 5 business days theo snapshot của order.</p></div></div><div class="production-step"><span class="step-number">3</span><div><strong>Chờ Kenji duyệt</strong><p>Review bản thảo synthetic; có thể yêu cầu chỉnh sửa.</p></div></div><div class="production-step"><span class="step-number">4</span><div><strong>Revision window</strong><p>7 ngày theo snapshot, không bị sửa bởi cài đặt mới.</p></div></div><div class="production-step"><span class="step-number">5</span><div><strong>Ready nhưng delivery bị B4 chặn</strong><p>Không có public/private object thật cho đến khi Private Storage gate được đóng.</p></div></div></section><div class="button-set">${action('Mở đơn HM-018','go-hatmam-detail')} ${action('Review publication','go-publication')}</div>`);
  }

  function renderPublication() {
    return page('Xuất bản riêng tư', 'Publication synthetic — xem metadata và checksum, nhưng không upload, phát hành, hoặc xóa bất kỳ Storage object nào.', `
      <section class="grid two"><article class="card"><h2>Publication synthetic · PUB-013</h2><div class="kv"><div class="muted">Trạng thái</div><div>${badge(data.publication,statusTone(data.publication))}</div><div class="muted">Metadata</div><div>draft-hat-mam-013.pdf · synthetic only</div><div class="muted">Checksum</div><div><code>sha256: demo-7d13…c12a</code></div><div class="muted">Private Storage</div><div>${badge('CHƯA SẴN SÀNG','blocked')}</div></div><div class="button-set">${action('Yêu cầu chỉnh sửa','pub-revise')} ${action('Duyệt publication giả','pub-approve')} ${action('Thu hồi publication giả','pub-revoke','button-danger')}</div></article>
      <article class="card"><h2>Điều gì không xảy ra</h2><ul class="timeline"><li><time>Storage</time>Không upload object, không tạo signed URL.</li><li><time>Delivery</time>Không gửi email, không public activate.</li><li><time>Revoke</time>Chỉ đổi local state, không xóa object hoặc metadata thật.</li></ul><div class="callout fail">Delivery bị B4 chặn phù hợp: <strong>private_storage_ready=false</strong>.</div></article></section>
      <section class="card" style="margin-top:14px"><h2>Review và chỉnh sửa</h2><p class="small">Thử duyệt, yêu cầu chỉnh sửa, duyệt lại hoặc thu hồi để xem audit history synthetic thay đổi.</p></section>`);
  }

  function renderDeletion() {
    return page('Xóa dữ liệu & retention', 'Deletion preview — không xóa thật. Hard gate vẫn đóng: deletion_workflow_ready=false.', `
      <div class="notice"><strong>Thứ tự bắt buộc:</strong> object trước metadata. Nhưng demo này không gọi Storage, SQL hay endpoint xóa nào.</div>
      <section class="grid two"><article class="card"><h2>DEL-004 · yêu cầu giả</h2><div class="kv"><div class="muted">Trạng thái</div><div>${badge(data.deletion,statusTone(data.deletion))}</div><div class="muted">Raw child intake</div><div>Retention 12 tháng · synthetic preview</div><div class="muted">Private room/publication</div><div>Retention 24 tháng · synthetic preview</div><div class="muted">Early deletion</div><div>Được yêu cầu trong fixture</div></div><div class="button-set">${action('Xem affected records','deletion-preview')} ${action('Xác nhận thao tác giả','deletion-confirm')} ${action('Thử lại','deletion-retry')}</div></article>
      <article class="card"><h2>Execution order preview</h2><ol class="timeline"><li><time>Bước 1 · nếu gate mở</time>Xác minh private object list.</li><li><time>Bước 2 · nếu gate mở</time>Xóa object thành công trước.</li><li><time>Bước 3 · nếu gate mở</time>Chỉ sau đó xóa metadata/records.</li><li><time>Bước 4 · hiện tại</time>Ghi audit fail-closed, không làm gì thật.</li></ol></article></section>
      <div class="callout fail" style="margin-top:14px"><strong>FAIL-CLOSED:</strong> Storage và destructive SQL bị cấm trong demo. Retry chỉ tạo synthetic audit evidence.</div>`);
  }

  function renderSettings() {
    const v = data.settings;
    return page('Cài đặt theo phiên bản', 'Cài đặt demo có validation phía giao diện để review UX. Admin thật có validation server-side riêng.', `
      <section class="grid two"><article class="card"><h2>Phiên bản mới (giả)</h2><form id="settings-form"><div class="form-grid"><div class="field"><label for="price">Giá Hạt Mầm (VND)</label><input id="price" name="price" type="number" min="100000" value="${v.price}" /></div><div class="field"><label for="capacity">Capacity / tháng</label><input id="capacity" name="capacity" type="number" min="1" max="50" value="${v.capacity}" /></div><div class="field"><label for="delivery">Giao trong (business days)</label><input id="delivery" name="delivery" type="number" min="1" max="30" value="${v.delivery}" /></div><div class="field"><label for="revision">Revision window (days)</label><input id="revision" name="revision" type="number" min="1" max="30" value="${v.revision}" /></div><div class="field"><label for="retention">Raw intake retention (tháng)</label><input id="retention" name="retention" type="number" min="1" max="60" value="${v.retention}" /></div></div><div class="button-set"><button class="button" type="submit">Lưu phiên bản demo mới</button></div></form><p class="small">Release/provider flags tiếp tục khóa OFF và không có control nào để bật.</p></article>
      <article class="card"><h2>Snapshot cũ không đổi</h2><div class="callout"><strong>HM-018 đã snapshot</strong><br>Hạt Mầm · ₫1.500.000 · 5 business days · revision 7 ngày · raw intake 12 tháng.</div><p class="small">Dù tạo phiên bản demo mới, order đã tồn tại vẫn giữ các giá trị này.</p></article></section>
      <section class="card" style="margin-top:14px"><h2>Lịch sử phiên bản</h2><div class="table-wrap"><table class="table"><thead><tr><th>Phiên bản</th><th>Thời gian</th><th>Giá Hạt Mầm</th><th>Sức chứa</th><th>Trạng thái</th></tr></thead><tbody>${data.versions.map(vr=>`<tr><td>${vr.number}</td><td>${vr.time}</td><td>₫${Number(vr.price).toLocaleString('vi-VN')}</td><td>${vr.capacity}/tháng</td><td>${badge(vr.label || 'Lịch sử', vr.label ? 'ready' : '')}</td></tr>`).join('')}</tbody></table></div></section>`);
  }

  function renderAudit() {
    return page('Lịch sử thao tác', 'Lịch sử này là dữ liệu giả, chỉ tồn tại trong trình duyệt hiện tại.', `<section class="card"><ul class="timeline">${data.audit.map(item=>`<li><time>${esc(item.time)}</time>${esc(item.text)}</li>`).join('')}</ul></section><p class="small">Không có event nào được gửi về database, analytics hoặc service provider.</p>`);
  }

  function renderReadiness() {
    return page('Mức sẵn sàng & gate phát hành', 'Không gate nào bị gọi là pass. Đây là bảng review để thấy rõ hệ thống thật còn bị khóa.', `<section class="grid two"><article class="card"><h2>Gate phát hành</h2><div class="readiness"><div class="readiness-row"><span>Lưu trữ riêng / B4</span>${badge('OPEN — OFF','blocked')}</div><div class="readiness-row"><span>Quy trình xóa thật</span>${badge('OPEN — OFF','blocked')}</div><div class="readiness-row"><span>Auth / AAL2</span>${badge('OPEN — chưa review thật','blocked')}</div><div class="readiness-row"><span>Security Advisor mới</span>${badge('OPEN','blocked')}</div><div class="readiness-row"><span>Resend</span>${badge('OFF','blocked')}</div><div class="readiness-row"><span>Cal.com</span>${badge('OFF','blocked')}</div><div class="readiness-row"><span>Kích hoạt công khai</span>${badge('OFF','blocked')}</div></div></article><article class="card"><h2>Ranh giới demo</h2><p class="small">Demo này không khép bất kỳ gate phát hành nào. Nó được tạo duy nhất để Founder review UX, thuật ngữ, ưu tiên công việc và trạng thái trước khi Admin thật lên canonical domain.</p><div class="callout fail">Không có Supabase, API, provider, service-role, dữ liệu khách hay trẻ em thật trong deployment này.</div></article></section>`);
  }

  function renderDataPublication() {
    return page('Dữ liệu & ấn phẩm', 'Dữ liệu cá nhân trẻ em — phạm vi vận hành hạn chế. Chỉ lưu kết luận cần thiết, không lưu toàn bộ câu chuyện.', `<section class="grid two"><article class="card"><h2>Dữ liệu và retention</h2><p class="small">Demo chỉ có fixture. Hệ thống thật giữ dữ liệu riêng, không công khai, có consent, retention, deletion, RLS và MFA/AAL2.</p><div class="button-set">${action('Xem deletion preview','go-deletion')} ${action('Xem lịch sử thao tác','go-audit')}</div></article><article class="card"><h2>Ấn phẩm riêng tư</h2><p class="small">Xem metadata/checksum synthetic. Lưu trữ riêng vẫn OFF nên không upload, phát hành hay xóa object thật.</p><div class="button-set">${action('Mở ấn phẩm','go-publication')}</div></article></section><section class="card" style="margin-top:14px"><h2>Không thu thập mặc định</h2><p class="small">Không địa chỉ đầy đủ, trường/lớp, giấy tờ, sức khỏe, chẩn đoán, biometrics, ảnh/video/audio, transcript đầy đủ hoặc chi tiết gia đình không cần cho sản phẩm.</p></section>`);
  }

  function renderSystem() {
    return page('Hệ thống', 'Trạng thái kỹ thuật được ghi đúng sự thật; demo không kết nối bất kỳ dịch vụ vận hành nào.', `<section class="grid two"><article class="card"><h2>Tình trạng hệ thống</h2><div class="readiness"><div class="readiness-row"><span>Database</span>${badge('KHÔNG KẾT NỐI','blocked')}</div><div class="readiness-row"><span>Lưu trữ riêng</span>${badge('OFF','blocked')}</div><div class="readiness-row"><span>Email / Lịch</span>${badge('OFF','blocked')}</div><div class="readiness-row"><span>AI</span>${badge('CHƯA KẾT NỐI','blocked')}</div><div class="readiness-row"><span>Backup</span>${badge('CHỈ MINH HỌA','pending')}</div><div class="readiness-row"><span>Gate công khai</span>${badge('OFF','blocked')}</div></div></article><article class="card"><h2>Quản trị demo</h2><p class="small">Các thay đổi chỉ nằm trong localStorage của trình duyệt hiện tại. Không có API, secret, provider hay dữ liệu thật.</p><div class="button-set">${action('Khách quan tâm & email','go-growth')} ${action('Cài đặt theo phiên bản','go-settings')} ${action('Mức sẵn sàng','go-readiness')} ${action('Liên hệ','go-contact')}</div></article></section>`);
  }

  function renderGrowth() {
    return page('Khách quan tâm & entry', 'Tất cả danh sách, email và chuyển đổi ở đây là dữ liệu giả; không có địa chỉ email thật.', `<section class="grid stats">${stat('Tổng khách quan tâm',data.leads)}${stat('Đã đồng ý nurture','18')}${stat('Đã dừng nhận tin','3')}${stat('Chuyển sang assessment','4')}</section><section class="grid two" style="margin-top:14px"><article class="card"><h2>Ebook</h2><p>${badge(data.ebook.status,statusTone(data.ebook.status))}</p><p class="small">${esc(data.ebook.name)} · ${esc(data.ebook.route)}</p><div class="button-set">${action('Cấu hình ebook','go-ebook')} ${action('Thử journey ebook','ebook-journey')}</div></article><article class="card"><h2>Bộ câu hỏi</h2><p>${badge('50.000 VND · DỮ LIỆU GIẢ','pending')}</p><p class="small">“Tôi đang ở đâu?” · version 0 · rules deterministic · không AI scoring.</p><div class="button-set">${action('Mở journey assessment','go-assessment')} ${action('Email chăm sóc','go-nurture')}</div></article></section><section class="card" style="margin-top:14px"><h2>Khách quan tâm — danh sách giả</h2><div class="table-wrap"><table class="table"><thead><tr><th>Mã lead</th><th>Nguồn ebook</th><th>Consent</th><th>Email gần nhất</th><th>Chuyển đổi</th><th>Trạng thái</th></tr></thead><tbody><tr><td>LEAD-024</td><td>Campaign mẫu</td><td>${badge('NURTURE ĐỒNG Ý','ready')}</td><td>Ebook delivery (giả)</td><td>Assessment</td><td>${badge('ĐANG NHẬN','pending')}</td></tr><tr><td>LEAD-021</td><td>Reading route mẫu</td><td>${badge('CHỈ EMAIL VẬN HÀNH','pending')}</td><td>Không có</td><td>—</td><td>${badge('KHÔNG NURTURE','blocked')}</td></tr><tr><td>LEAD-019</td><td>Campaign mẫu</td><td>${badge('ĐÃ HỦY ĐĂNG KÝ','blocked')}</td><td>Nurture #2 (giả)</td><td>Core offer</td><td>${badge('DỪNG','blocked')}</td></tr></tbody></table></div></section>`);
  }

  const productRows = [
    ['Ebook & Góc đọc','Khám phá miễn phí','Bản nháp','Email/route chưa kết nối','Asset, consent, reading route, provider','Hoàn thiện contract'],
    ['Tôi đang ở đâu?','Người lớn','Bản nháp · 50.000 VND','Rule deterministic v0','Câu hỏi, rule, kết quả, email Founder duyệt','Duyệt contract assessment'],
    ['Lặng 90’','Người lớn','Kiến trúc canonical','Provider thực OFF','Auth/AAL2, payment, Cal.com, real E2E','Đóng release gates'],
    ['Bạn Là Duy Nhất','Người lớn','Xem trước','Ấn phẩm riêng tư chưa kết nối','Form, giá, SLA, revision, policy','Duyệt product contract'],
    ['Dấu Ấn Của Bạn','Người lớn','Xem trước','Session 150 phút + ấn phẩm','Giá, form, refund, booking, fulfilment','Duyệt product contract'],
    ['Hạt Mầm · HM-01','Phụ huynh / 0–7','Canonical · public blocked','2m launch / 3m reference','Storage, deletion, real E2E','Giữ gates OFF'],
    ['Hạt Mầm · HM-02','Phụ huynh / 0–7','Canonical · public blocked','3.5m launch / 5.5m reference','Storage, deletion, real E2E','Giữ gates OFF'],
    ['Bản Sắc Khám Phá','7–14','Xem trước','Không kế thừa Hạt Mầm','Giá, form, consent, workflow riêng','Duyệt contract riêng'],
    ['Bản Sắc Giao Mùa','14–21','Xem trước','Autonomy boundary mở','Participation, access, change, deletion','Founder decision riêng'],
    ['KIDMAP / payments cũ','Legacy','Legacy','Cô lập','Không cấu hình/migrate/reuse','Không tác động']
  ];
  function productTable() { return `<div class="table-wrap"><table class="table"><thead><tr><th>Sản phẩm</th><th>Đối tượng</th><th>Trạng thái</th><th>Giá / workflow</th><th>Thiếu / gate</th><th>Bước được phép</th></tr></thead><tbody>${productRows.map(r=>`<tr>${r.map((c,i)=>`<td>${i===2?badge(c,statusTone(c)):esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }

  function renderWork() {
    return page('Công việc', 'Các hàng chờ theo việc Kenji cần làm. Chỉ Lặng và Hạt Mầm có fixture thao tác; mọi ấn phẩm khác là preview contract.', `<section class="grid two"><article class="card"><h2>Lặng</h2><p>${badge('CANONICAL · EXTERNAL GATES OPEN','pending')}</p><p class="small">Intake 6 câu → Human Decision Gate → payment → booking riêng. Không AI quyết định, không booking trước payment.</p><div class="button-set">${action('Mở Lặng','go-lang')} ${action('Mở payment','go-payment')}</div></article><article class="card"><h2>Ấn phẩm người lớn</h2><p>${badge('2 PREVIEW CONTRACTS','pending')}</p><p class="small">Bạn Là Duy Nhất và Dấu Ấn Của Bạn không có route, form hay delivery thật.</p><div class="button-set">${action('Xem kiến trúc','go-adult-publications')}</div></article><article class="card"><h2>Bản Sắc Của Con</h2><p>${badge('HM CANONICAL · PUBLIC BLOCKED','blocked')}</p><p class="small">HM-01/HM-02 tách package snapshot. Khám Phá/Giao Mùa là preview độc lập.</p><div class="button-set">${action('Mở Hạt Mầm','go-hatmam')} ${action('Xem preview line','go-child-preview')}</div></article><article class="card"><h2>Dữ liệu, payment & publication</h2><p class="small">Evidence và các thao tác destructive đều chỉ là fixture fail-closed.</p><div class="button-set">${action('Payment','go-payment')} ${action('Dữ liệu & ấn phẩm','go-data-publication')}</div></article></section>`);
  }

  function renderAdultPublications() {
    return page('Ấn phẩm người lớn', 'Hai contract preview để review cấu trúc trước khi có Founder approval sản phẩm riêng.', `<section class="grid two"><article class="card"><h2>Bạn Là Duy Nhất</h2>${badge('XEM TRƯỚC','pending')}<ol class="timeline"><li><time>1</time>Intake (chưa duyệt)</li><li><time>2</time>Payment request → Kenji xác nhận thật</li><li><time>3</time>Sản xuất → Kenji review → revision nếu contract cho phép</li><li><time>4</time>Private reading room + PDF (Storage OFF)</li></ol><p class="small">Thiếu: câu hỏi, chapter template, SLA, revision, giá và chính sách.</p></article><article class="card"><h2>Dấu Ấn Của Bạn</h2>${badge('XEM TRƯỚC','pending')}<ol class="timeline"><li><time>1</time>Intake / Kenji review nếu được duyệt</li><li><time>2</time>Payment → Kenji xác nhận thật</li><li><time>3</time>Private booking → session 150 phút</li><li><time>4</time>Ấn phẩm hai lớp → review → delivery riêng</li></ol><p class="small">Thiếu: giá, form, refund, booking và fulfilment terms.</p></article></section><div class="button-set">${action('Quay lại Công việc','go-work')} ${action('Xem catalog','go-catalog')}</div>`);
  }

  function renderChildPreview() {
    return page('Bản Sắc Khám Phá & Giao Mùa', 'Không dùng Hạt Mầm làm mặc định. Mỗi sản phẩm cần contract, consent và activation riêng.', `<section class="grid two"><article class="card"><h2>Khám Phá · 7–14</h2>${badge('XEM TRƯỚC','pending')}<p>Có thể dùng blocks đã duyệt, nhưng giá, form, consent và logic kết quả không tự kế thừa Hạt Mầm.</p><p class="small">Next allowed: Founder duyệt product-specific contract.</p></article><article class="card"><h2>Giao Mùa · 14–21</h2>${badge('XEM TRƯỚC · AUTONOMY OPEN','blocked')}<p>Phải quyết định awareness/participation của người trẻ, quyền truy cập ấn phẩm, sửa đổi và deletion trước implementation.</p><p class="small">Next allowed: Founder decision về autonomy boundary.</p></article></section><div class="button-set">${action('Quay lại Công việc','go-work')} ${action('Mở workflow library','go-workflows')}</div>`);
  }

  const libraryItems = [
    { id:'assessment-01', title:'Tôi đang ở đâu? · kết quả mẫu', product:'Assessment', state:'Sẵn sàng đọc', access:'Đang hoạt động', version:'v1 · rule deterministic', date:'02/08/2026', kind:'Kết quả', intro:'Kết quả quan sát dành riêng cho lần trả lời này; không phải chẩn đoán hay dự đoán.', chapters:['Kết quả của bạn','Điểm quan sát','Bước tiếp theo'] },
    { id:'hm-preparing', title:'Bản Sắc Hạt Mầm · đơn HM-018', product:'Hạt Mầm HM-01', state:'Đang chuẩn bị', access:'Đang chuẩn bị', version:'Chưa có bản giao', date:'—', kind:'Ấn phẩm', intro:'Kenji đang chuẩn bị ấn phẩm. Nội dung đọc sẽ xuất hiện khi bản được duyệt.', chapters:[] },
    { id:'hm-ready', title:'Bản Sắc Hạt Mầm · đơn HM-013', product:'Hạt Mầm HM-02', state:'Sẵn sàng đọc', access:'Đang hoạt động', version:'v2', date:'03/08/2026', kind:'Ấn phẩm', intro:'Một ấn phẩm đã sẵn sàng đọc riêng tư.', chapters:['Lời mở đầu','Bản sắc đang lớn','Gợi ý trò chuyện'] },
    { id:'adult-01', title:'Bạn Là Duy Nhất · bản mẫu', product:'Ấn phẩm người lớn', state:'Sẵn sàng đọc', access:'Đang hoạt động', version:'v1', date:'03/08/2026', kind:'Ấn phẩm', intro:'Một phòng đọc riêng cho ấn phẩm cá nhân hoá.', chapters:['Mở đầu','Những điều đã nhìn rõ','Ghi chú tiếp nối'] },
    { id:'updated-01', title:'Dấu Ấn Của Bạn · bản mẫu', product:'Ấn phẩm người lớn', state:'Có bản cập nhật', access:'Đang hoạt động', version:'v2 · cập nhật từ v1', date:'04/08/2026', kind:'Ấn phẩm', intro:'Bản hiện tại có một cập nhật đã được duyệt.', chapters:['Lớp một','Lớp hai','Điều được bổ sung'], update:'Bổ sung ghi chú làm rõ theo revision đã duyệt.' }
  ];
  function libraryItem(id) { return libraryItems.find(item=>item.id===id) || libraryItems[0]; }
  function customerStateTone(value) { return /sẵn sàng|cập nhật|hoạt động/i.test(value)?'ready':/không còn|lưu trữ/i.test(value)?'blocked':'pending'; }
  function renderLibrary() {
    const groups=['Đang chuẩn bị','Sẵn sàng đọc','Có bản cập nhật','Đã lưu trữ','Không còn quyền truy cập'];
    return page('Thư viện của tôi · demo', 'Một không gian khách hàng giả, dựa trên entitlement fixture. Không có email thật, magic link, tài khoản, PDF hay dữ liệu cá nhân.', `<div class="notice"><strong>Ranh giới trả phí.</strong> Ebook Góc đọc công khai không nằm trong Thư viện này; nó được đọc tự do, không cần entitlement. Các trạng thái dưới đây chỉ là paid/private fixture.</div>${groups.map(group=>{const items=libraryItems.filter(item=>item.state===group);return `<section class="card" style="margin-top:14px"><h2>${group}</h2>${items.length?`<div class="grid two">${items.map(item=>`<article class="card"><p class="section-label">${esc(item.kind)} · ${esc(item.product)}</p><h3>${esc(item.title)}</h3><p>${badge(item.state,customerStateTone(item.state))} ${badge(`Quyền truy cập: ${item.access}`,customerStateTone(item.access))}</p><p class="small">${esc(item.version)}${item.date==='—'?'':` · giao ${item.date}`}</p>${item.update?`<p class="small"><strong>Cập nhật:</strong> ${esc(item.update)}</p>`:''}<div class="button-set">${action(item.state==='Đang chuẩn bị'?'Xem trạng thái':'Mở phòng đọc',`open-room-${item.id}`)}</div></article>`).join('')}</div>`:'<p class="small">Chưa có mục mẫu ở trạng thái này.</p>'}</section>`}).join('')}<section class="card" style="margin-top:14px"><h2>Khôi phục quyền truy cập</h2><p class="small">Tương lai: dùng email mua hàng đã xác minh để nhận một magic link mới. Hỗ trợ không thể tiết lộ link của người khác. Không có link thật được tạo trong demo.</p></section><div class="button-set">${action('Mở Góc đọc công khai','go-public-reading')} ${action('Quay lại Tổng quan','go-overview')}</div>`);
  }
  function renderReadingRoom() {
    const item=libraryItem(data.library.item); const chapter=Math.min(Math.max(1,data.library.chapter),Math.max(1,item.chapters.length)); const ready=item.state!=='Đang chuẩn bị'; const chapterName=ready?item.chapters[chapter-1]:''; const displayVersion=item.id==='updated-01' && data.library.revisionApplied?'v3 · revision mới đã duyệt':item.version;
    return page(item.title, item.intro, `<div class="notice"><strong>Phòng đọc riêng · demo.</strong> Chỉ là fixture local. Bản thật cần verified identity, entitlement isolation, private Storage và link download ký ngắn hạn.</div><section class="grid two"><article class="card"><h2>Thông tin bản đọc</h2><div class="kv"><div class="muted">Sản phẩm</div><div>${esc(item.product)}</div><div class="muted">Bản hiện tại</div><div>${esc(displayVersion)}</div><div class="muted">Ngày giao</div><div>${esc(item.date)}</div><div class="muted">Quyền truy cập</div><div>${badge(item.access,customerStateTone(item.access))}</div>${item.update?`<div class="muted">Thông báo cập nhật</div><div>${esc(item.update)}</div>`:''}</div></article><article class="card"><h2>Đọc an toàn</h2><p class="small">Bạn có thể đọc trên thiết bị này. Đừng chia sẻ link hoặc nội dung riêng tư. Khi cần hỗ trợ, hãy dùng nút hỗ trợ dưới đây.</p><p>${badge('NOINDEX · PRIVATE IN FUTURE','pending')}</p><div class="button-set">${action('Tải PDF A5 (minh họa)','simulate-pdf')} ${action('Cần hỗ trợ','support-request')}</div><p class="small">PDF thật được tạo và checksum trước delivery; mỗi download phải kiểm tra quyền. Demo không có file PDF.</p></article></section>${ready?`<section class="grid two" style="margin-top:14px"><article class="card"><h2>Mục lục</h2><ol class="timeline">${item.chapters.map((name,index)=>`<li><time>${index+1}</time><button class="link-button" data-action="chapter-${item.id}-${index+1}">${esc(name)}</button></li>`).join('')}</ol></article><article class="card"><p class="section-label">CHƯƠNG ${chapter}/${item.chapters.length}</p><h2>${esc(chapterName)}</h2><p>Đây là đoạn đọc HTML mẫu để Founder review trải nghiệm. Không có nội dung khách hàng, trẻ em hoặc ấn phẩm thật.</p><p class="small">Tiến độ được giữ trên thiết bị hiện tại trong demo. Bản sản phẩm thật chỉ ghi access/progress theo contract đã duyệt.</p><div class="button-set">${chapter>1?action('Quay lại','chapter-prev'):''}${chapter<item.chapters.length?action('Tiếp theo','chapter-next'):''}</div></article></section>`:`<section class="card" style="margin-top:14px"><h2>Đang chuẩn bị</h2><p>Thông tin của bạn đã được nhận và thanh toán đã xác nhận. Kenji đang chuẩn bị bản đọc; mục này chưa có nội dung để mở.</p></section>`}<section class="card" style="margin-top:14px"><h2>Phiên bản, revision & quyền truy cập</h2><p class="small">Revision đã duyệt tạo phiên bản mới bất biến; bản cũ được giữ nội bộ. Khách hàng mặc định xem bản mới nhất, không có lịch sử download trừ khi contract riêng cho phép.</p><div class="button-set">${item.id==='updated-01'?action('Mô phỏng cập nhật revision','simulate-revision'):''}${action('Quay lại Thư viện','go-library')}</div></section>`);
  }

  function renderCatalog() {
    return page('Sản phẩm & quy trình', 'Catalog trung tâm: mỗi sản phẩm có state độc lập; có trang không đồng nghĩa được bán hoặc active.', `<div class="notice"><strong>State model:</strong> Bản nháp → Xem trước → Sẵn sàng nội bộ → Đã kiểm thử → Chờ Founder mở → Đang hoạt động; có thể Tạm dừng, Ngừng nhận mới, Lưu trữ hoặc Legacy. Indexing luôn là quyết định M6 riêng.</div><div class="button-set" style="margin:14px 0">${action('Thêm sản phẩm giả','go-wizard')} ${action('Workflow library','go-workflows')} ${action('Giá & policy version','go-business-config')} ${action('Release checklists','go-product-readiness')}</div>${productTable()}`);
  }

  function renderWorkflows() {
    const blocks=['Khám phá / email capture / consent','Lead delivery / nurture','Intake / assessment / deterministic scoring','Kenji Decision Gate / yêu cầu thêm thông tin','Payment request / report / evidence / xác nhận','Booking / session','Sản xuất / review / revision / final approval','Private publication / email delivery / follow-up','Retention / deletion / audit'];
    return page('Workflow library', 'Founder chỉ có thể ghép block đã được duyệt sau khi backend thật tồn tại. Thiếu block là software/governance change.', `<section class="card"><h2>Block đã được chuẩn bị</h2><ul class="timeline">${blocks.map((b,i)=>`<li><time>${i+1}</time>${b}</li>`).join('')}</ul></section><section class="card" style="margin-top:14px"><h2>Ví dụ binding</h2><p class="small">Ebook: capture → operational consent → delivery → optional nurture. Assessment: versioned questions → result locked → payment evidence → deterministic result → email. Lặng: intake → Kenji decision → payment → booking. Hạt Mầm: intake/consent → snapshot → payment → production/review → private delivery → retention/deletion.</p></section><div class="button-set">${action('Quay lại catalog','go-catalog')} ${action('Thêm sản phẩm giả','go-wizard')}</div>`);
  }

  function renderBusinessConfig() {
    return page('Giá, chính sách & cấu hình', 'So sánh phiên bản chỉ minh họa. Snapshot của order cũ không bao giờ bị ghi đè bởi cài đặt mới.', `<section class="grid two"><article class="card"><h2>Phiên bản package Hạt Mầm</h2><div class="kv"><div class="muted">HM-01 launch / reference</div><div>2.000.000 / 3.000.000 VND</div><div class="muted">HM-02 launch / reference</div><div>3.500.000 / 5.500.000 VND</div><div class="muted">SLA / revision</div><div>5 ngày làm việc / 7 ngày</div><div class="muted">Retention</div><div>Raw intake 12 tháng / publication 24 tháng</div></div><p class="small">Áp dụng tương lai sau real implementation, không tự activate public flow.</p></article><article class="card"><h2>Configuration hay software?</h2><p>${badge('FOUNDER CONFIGURATION','ready')}</p><p class="small">Tên, label, giá/reference, effective date, capacity, SLA, policy copy, câu hỏi/email đã duyệt, block đã có, release request.</p><p>${badge('SOFTWARE / GOVERNANCE','blocked')}</p><p class="small">Capability/state/scoring/provider/payment automation/data category/access/deletion/AI/public activation/indexing mới → Draft PR, tests và Founder approval.</p></article></section><div class="button-set">${action('Cài đặt phiên bản demo','go-settings')} ${action('Quay lại catalog','go-catalog')}</div>`);
  }

  function renderProductReadiness() {
    return page('Release checklist theo sản phẩm', 'Không product nào được gắn “sẵn sàng” khi provider hoặc real E2E chưa được xác minh.', `<section class="table-wrap"><table class="table"><thead><tr><th>Sản phẩm</th><th>Contract / copy / form</th><th>Payment / provider</th><th>Privacy / delivery</th><th>Trạng thái honest</th></tr></thead><tbody><tr><td>Ebook</td><td>OPEN</td><td>Resend OFF</td><td>Consent/route OPEN</td><td>${badge('BẢN NHÁP','blocked')}</td></tr><tr><td>Assessment 50k</td><td>Question/rule/result OPEN</td><td>Manual payment contract OPEN</td><td>Real E2E/email OFF</td><td>${badge('BẢN NHÁP','blocked')}</td></tr><tr><td>Lặng</td><td>Canonical</td><td>Cal.com/payment E2E OPEN</td><td>Auth/AAL2 real evidence OPEN</td><td>${badge('KHÔNG ACTIVE','blocked')}</td></tr><tr><td>Hạt Mầm</td><td>Canonical HM-01/HM-02</td><td>Payment E2E OPEN</td><td>Storage/deletion OPEN</td><td>${badge('PUBLIC BLOCKED','blocked')}</td></tr><tr><td>Preview contracts</td><td>Founder inputs OPEN</td><td>OFF</td><td>OFF</td><td>${badge('XEM TRƯỚC','pending')}</td></tr></tbody></table></section><div class="callout fail" style="margin-top:14px">“Chờ Founder mở” chỉ có sau khi mọi checklist riêng, real provider E2E, monitoring, backup/rollback và feature flag OFF review hoàn tất. Product activation không thay indexing M6.</div><div class="button-set">${action('Quay lại catalog','go-catalog')}</div>`);
  }

  function renderWizard() {
    const starts=['Tạo từ mẫu có sẵn','Sao chép cấu trúc của một sản phẩm','Bắt đầu bản nháp trống']; const steps=['Thông tin cơ bản','Đối tượng','Gói và giá','Biểu mẫu','Workflow','Thanh toán','Giao sản phẩm','Chính sách','Email','Sức chứa','Dữ liệu và retention','Review','Release checklist']; const w=data.wizard;
    return page('Thêm sản phẩm — synthetic wizard', 'Wizard chỉ lưu một bản nháp trong localStorage. Nó không tạo route, table, form, email, payment, public product hay active offer.', `<section class="grid two"><article class="card"><h2>Bắt đầu</h2>${starts.map((s,i)=>`<p>${action(s,`wizard-start-${i}`,'button-secondary')} ${w.start===i?badge('ĐÃ CHỌN','ready'):''}</p>`).join('')}<p class="small">Mẫu có thể: ebook, paid assessment, private session, personalised publication, session + publication, parent/child publication.</p></article><article class="card"><h2>Bước ${w.step}/13 · ${steps[w.step-1]}</h2><p class="small">${w.start===null?'Chọn một cách bắt đầu trước.':'Nội dung bước này là khung review; real implementation cần contract và gates riêng.'}</p><div class="button-set">${w.step>1?action('Quay lại','wizard-back'):''}${w.step<13?action('Tiếp theo','wizard-next'):action('Lưu bản nháp local','wizard-save')}</div>${w.saved?`<p>${badge('BẢN NHÁP LOCAL ĐÃ LƯU','ready')}</p>`:''}</article></section><section class="card" style="margin-top:14px"><h2>Release boundary</h2><p class="small">Save không kích hoạt gì. “Đang hoạt động” không thể được tạo bằng wizard; route, provider, consent, payment, privacy, real E2E và Founder activation đều là gates tách riêng.</p></section><div class="button-set">${action('Quay lại catalog','go-catalog')}</div>`);
  }

  function renderEbook() {
    return page('Ebook', 'Cấu hình giả để duyệt UX. Không có asset, reading route, email capture hoặc gửi email thật.', `<section class="grid two"><article class="card"><h2>Cấu hình ebook giả</h2><form id="ebook-form"><div class="field"><label for="ebook-name">Tên ebook</label><input id="ebook-name" name="name" value="${esc(data.ebook.name)}" /></div><div class="field"><label for="ebook-route">Reading route</label><input id="ebook-route" name="route" value="${esc(data.ebook.route)}" /></div><div class="field"><label for="ebook-status">Trạng thái</label><select id="ebook-status" name="status"><option ${data.ebook.status==='Tạm dừng'?'selected':''}>Tạm dừng</option><option ${data.ebook.status==='Hoạt động giả'?'selected':''}>Hoạt động giả</option></select></div><div class="button-set"><button class="button" type="submit">Lưu cấu hình demo</button></div></form></article><article class="card"><h2>Journey ebook</h2><ol class="timeline"><li><time>1</time>Visitor giả nhập email.</li><li><time>2</time>Chỉ email vận hành được ghi nhận cho delivery.</li><li><time>3</time>Reading access và delivery email giả.</li><li><time>4</time>Nurture chỉ khi có consent marketing riêng.</li></ol><div class="button-set">${action('Chạy journey ebook giả','ebook-journey')} ${action('Email chăm sóc','go-nurture')}</div></article></section>`);
  }

  function renderAssessment() {
    const stage=data.assessment.stage; const steps=['Email entered','Questions answered','Result locked','Transfer reported','Payment confirmed','Result delivered']; const reached=Math.max(0,['Chưa bắt đầu',...steps].indexOf(stage));
    return page('Bộ câu hỏi — “Tôi đang ở đâu?”', 'Assessment synthetic: 50.000 VND, version 0, 6 câu hỏi mẫu. Đây không phải chẩn đoán, dự đoán hay quyết định điều kiện.', `<section class="grid two"><article class="card"><h2>Trạng thái journey</h2><div class="kv"><div class="muted">Giá hiện tại</div><div>50.000 VND</div><div class="muted">Payment requirement</div><div>Founder xác nhận thủ công</div><div class="muted">Trạng thái</div><div>${badge(stage,statusTone(stage))}</div><div class="muted">Email result</div><div>${esc(data.assessment.sequence)}</div></div><div class="button-set">${reached<1?action('Nhập email giả','assessment-email'):''}${reached===1?action('Trả lời 6 câu giả','assessment-answers'):''}${reached===2?action('Yêu cầu thanh toán 50.000 VND','assessment-request-payment'):''}${reached===3?action('Báo đã chuyển khoản giả','assessment-report-transfer'):''}${reached===4?action('Founder xác nhận payment giả','assessment-confirm-payment'):''}${reached===5?action('Tạo kết quả deterministic','assessment-generate'):''}</div></article><article class="card"><h2>Rule engine demo</h2><p class="small">Input fixture: điểm “nhịp hiện tại” = 4/6, “độ rõ bước tiếp” = 3/6. Rule v0: tổng 7–9 → nhóm <strong>Nhìn rõ bước tiếp theo</strong>.</p><p>${data.assessment.result?badge(data.assessment.result,'ready'):badge('KẾT QUẢ ĐANG KHÓA','blocked')}</p><p class="small">Cùng input + cùng version luôn ra cùng nhóm. AI không thể đổi điểm hoặc category; template/kết quả lịch sử không được viết lại.</p></article></section><section class="card" style="margin-top:14px"><h2>Version contract</h2><p class="small">Future contract: assessment_versions, question_versions, answers, scoring_dimensions, deterministic_result_rules, result_template_versions, assessment_orders, payment confirmation, generated_results và delivery events. Nội dung câu hỏi, rule và result email thực vẫn <strong>chờ Founder duyệt</strong>.</p></section>`);
  }

  function renderNurture() {
    return page('Email chăm sóc', 'Sequence synthetic theo phiên bản. Không gửi email, không kết nối Resend và không có address thật.', `<section class="table-wrap"><table class="table"><thead><tr><th>Sequence</th><th>Thứ tự / delay</th><th>Subject</th><th>Stop condition</th><th>Goal</th><th>Trạng thái</th></tr></thead><tbody><tr><td>Ebook delivery</td><td>#1 · ngay</td><td>Gửi ebook giả</td><td>Delivery complete</td><td>Reading access</td><td>${badge('TẠM DỪNG','blocked')}</td></tr><tr><td>Ebook nurture</td><td>#2 · +3 ngày</td><td>Một ghi chép phù hợp</td><td>Unsubscribe / conversion</td><td>Assessment</td><td>${badge('TẠM DỪNG','blocked')}</td></tr><tr><td>Assessment result</td><td>#1 · sau payment confirmed</td><td>Kết quả của bạn</td><td>Delivery complete</td><td>Result access</td><td>${badge('TẠM DỪNG','blocked')}</td></tr><tr><td>Assessment follow-up</td><td>#2 · +5 ngày</td><td>Một bước tiếp theo</td><td>Unsubscribe / conversion</td><td>Relevant offer</td><td>${badge('TẠM DỪNG','blocked')}</td></tr></tbody></table></section><div class="notice" style="margin-top:14px">Email vận hành để giao ebook/kết quả tách khỏi consent marketing. Không bắt buộc marketing consent để nhận kết quả đã mua.</div>`);
  }

  function renderContact() {
    return page('Liên hệ', 'Module này hiển thị vì nó là một khu vực của Admin hiện tại; demo không gửi tin nhắn.', `<section class="card"><h2>Hộp thư vận hành — dữ liệu giả</h2><p class="small">Không có email, số điện thoại hay liên hệ thật. Resend chưa kết nối nên không có nút gửi.</p><div class="action-list"><div class="action-row"><div><strong>MSG-009 · Synthetic question</strong><p>Cần Kenji đọc trước 16:00.</p></div>${badge('CHỜ XỬ LÝ','pending')}</div><div class="action-row"><div><strong>MSG-008 · Synthetic follow-up</strong><p>Đã ghi chú trong browser demo.</p></div>${badge('ĐÃ XEM','ready')}</div></div></section>`);
  }

  let customerExperience; let publicReading;
  const renderers = { overview:renderOverview, growth:renderGrowth, work:renderWork, catalog:renderCatalog, library:renderLibrary, 'reading-room':renderReadingRoom, 'public-reading':()=>publicReading.renderReader(), 'assessment-landing':()=>publicReading.renderAssessment(), 'launch-core':()=>publicReading.renderLaunchCore(), 'customer-home':()=>customerExperience.renderHome(), 'cx-template':()=>customerExperience.renderTemplate(), 'cx-journey':()=>customerExperience.renderJourney(), 'cx-config':()=>customerExperience.renderConfig(), 'cx-landing':()=>customerExperience.renderLanding(), lang:renderLang, 'lang-detail':renderLangDetail, payments:renderPayments, hatmam:renderHatmam, 'hatmam-detail':renderHatmamDetail, production:renderProduction, publication:renderPublication, deletion:renderDeletion, settings:renderSettings, audit:renderAudit, readiness:renderReadiness, contact:renderContact, 'data-publication':renderDataPublication, system:renderSystem, ebook:renderEbook, assessment:renderAssessment, nurture:renderNurture, 'adult-publications':renderAdultPublications, 'child-preview':renderChildPreview, workflows:renderWorkflows, 'business-config':renderBusinessConfig, 'product-readiness':renderProductReadiness, wizard:renderWizard };
  function navView() { return ({'public-reading':'growth','assessment-landing':'growth','launch-core':'catalog','customer-home':'growth','cx-template':'growth','cx-journey':'growth','cx-config':'catalog','cx-landing':'growth',library:'growth','reading-room':'growth','lang':'work','lang-detail':'work','hatmam':'work','hatmam-detail':'work',production:'work',payments:'work',publication:'work',deletion:'work','data-publication':'work','adult-publications':'work','child-preview':'work',audit:'system',settings:'catalog',readiness:'system',contact:'system',ebook:'growth',assessment:'growth',nurture:'growth',workflows:'catalog','business-config':'catalog','product-readiness':'catalog',wizard:'catalog'})[data.view] || data.view; }
  function renderNav() { const active=navView(); navigation.innerHTML = nav.map(([id,label]) => `<button class="nav-button ${active===id?'active':''}" data-view="${id}">${label}</button>`).join(''); }
  function renderAssistant() { assistantPanel.innerHTML = data.assistantOpen ? `<section class="assistant-card"><h2>Hỏi Trợ lý</h2><p>Tóm tắt theo quy tắc trên dữ liệu giả — chưa kết nối AI thật.</p><ul><li>L-024 đang quá SLA và cần Kenji quyết định.</li><li>HM-018 có biên nhận đang chờ kiểm tra.</li><li>HM-011 quá hạn 1 ngày.</li><li>Lưu trữ riêng, email, lịch và kích hoạt công khai đều đang OFF.</li></ul><p class="small"><strong>Được phép trong tương lai:</strong> giải thích, tìm, tóm tắt, dự thảo và so sánh thay đổi. <strong>Không được:</strong> activate/publish/index, xác nhận payment, quyết định Lặng, score assessment, duyệt ấn phẩm, xóa dữ liệu, đổi Auth/MFA/quyền, kết nối provider hoặc đổi giá không có Founder confirmation. Mọi đề xuất phải có before/after, ảnh hưởng order tương lai/lịch sử và effective date.</p><div class="button-set">${action('Đóng','close-assistant')}</div></section>` : ''; }
  function render() { data.view = renderers[data.view] ? data.view : 'overview'; main.innerHTML = renderers[data.view](); renderNav(); renderAssistant(); location.hash = data.view; }
  function go(view) { data.view = view; data.assistantOpen = false; save(); render(); document.getElementById('sidebar').classList.remove('open'); document.getElementById('mobile-menu').setAttribute('aria-expanded','false'); main.focus({preventScroll:true}); }
  publicReading = window.EssencePublicReading({ getData:()=>data, page, badge, action, esc, audit, notice, go });
  customerExperience = window.EssenceCustomerExperience({ getData:()=>data, page, badge, action, esc, audit, notice, go });
  function handleAction(id) {
    const updates = {
      'go-overview':()=>go('overview'),'go-public-reading':()=>go('public-reading'),'go-launch-core':()=>go('launch-core'),'go-customer-home':()=>go('customer-home'),'go-library':()=>go('library'),'go-lang':()=>go('lang-detail'),'go-work':()=>go('work'),'go-catalog':()=>go('catalog'),'go-payment':()=>go('payments'),'go-deletion':()=>go('deletion'),'go-settings':()=>go('settings'),'go-hatmam':()=>go('hatmam'),'go-hatmam-detail':()=>go('hatmam-detail'),'go-publication':()=>go('publication'),'go-audit':()=>go('audit'),'go-system':()=>go('system'),'go-readiness':()=>go('readiness'),'go-contact':()=>go('contact'),'go-growth':()=>go('growth'),'go-ebook':()=>go('ebook'),'go-assessment':()=>go('assessment'),'go-nurture':()=>go('nurture'),'go-adult-publications':()=>go('adult-publications'),'go-child-preview':()=>go('child-preview'),'go-data-publication':()=>go('data-publication'),'go-workflows':()=>go('workflows'),'go-business-config':()=>go('business-config'),'go-product-readiness':()=>go('product-readiness'),'go-wizard':()=>go('wizard'),
      'ask-assistant':()=>{data.assistantOpen=true;notice('Trợ lý demo chỉ tóm tắt fixture trong trình duyệt.');},'close-assistant':()=>{data.assistantOpen=false;},
      'lang-read':()=>{data.langStatus='Đang đọc';audit('Kenji bắt đầu đọc L-024 trong demo.');notice('Đã chuyển L-024 sang “Đang đọc” trong dữ liệu demo.');},
      'lang-fit':()=>{data.langStatus='Phù hợp — chờ thanh toán';data.langDecision='Phù hợp';audit('Kenji ghi quyết định “Phù hợp” cho L-024 trong demo.');notice('Đã ghi quyết định giả. Payment chỉ là bước demo tiếp theo.');},
      'lang-more':()=>{data.langStatus='Cần thêm thông tin';data.langDecision='Chờ thêm';audit('Kenji yêu cầu thêm thông tin cho L-024 trong demo.');notice('Đã chuyển sang “Cần thêm thông tin” trong dữ liệu demo.');},
      'lang-no':()=>{data.langStatus='Chưa phù hợp';data.langDecision='Chưa phù hợp';audit('Kenji ghi quyết định “Chưa phù hợp” cho L-024 trong demo.');notice('Đã lưu trạng thái giả; không gửi email.');},
      'fake-booking':()=>{audit('Đã thử phát link đặt lịch giả; Cal.com vẫn OFF.');notice('FAIL-CLOSED: Cal.com chưa kết nối, không có booking thật.');},
      'confirm-payment':()=>{data.payment='Đã xác nhận — synthetic';data.hatmamStatus='Đã thanh toán';audit('Kenji xác nhận biên nhận giả HM-018 sau khi các điều kiện demo đều khớp.');notice('Payment synthetic đã xác nhận; không có giao dịch thật.');},
      'start-production':()=>{if(!data.payment.toLowerCase().includes('xác nhận')){notice('Bị chặn: cần xác nhận payment evidence giả trước.');return;}data.hatmamStatus='Đang sản xuất';audit('HM-018 được chuyển sang “Đang sản xuất” trong demo.');notice('Đã bắt đầu sản xuất giả.');},
      'queue-review':()=>{if(data.hatmamStatus!=='Đang sản xuất'){notice('Bị chặn: cần bắt đầu sản xuất trước.');return;}data.hatmamStatus='Chờ Kenji duyệt';audit('HM-018 được đưa vào chờ Kenji duyệt trong demo.');notice('Đã chuyển vào hàng review giả.');},
      'request-revision':()=>{data.hatmamStatus='Cần chỉnh sửa';audit('Kenji yêu cầu chỉnh sửa HM-018 trong demo.');notice('Đã yêu cầu revision giả; revision deadline vẫn là 15/08/2026.');},
      'approve-revision':()=>{if(data.hatmamStatus!=='Cần chỉnh sửa'){notice('Bị chặn: chỉ duyệt lại sau trạng thái cần chỉnh sửa.');return;}data.hatmamStatus='Chờ Kenji duyệt';audit('Bản revision HM-018 được đưa lại vào review trong demo.');notice('Đã duyệt vòng chỉnh sửa giả.');},
      'mark-ready':()=>{if(data.hatmamStatus!=='Chờ Kenji duyệt'){notice('Bị chặn: đơn cần ở trạng thái chờ Kenji duyệt.');return;}data.hatmamStatus='Sẵn sàng';audit('HM-018 được đánh dấu sẵn sàng; delivery vẫn bị B4 chặn.');notice('Sẵn sàng trong demo — delivery bị B4/Private Storage OFF chặn.');},
      'pub-revise':()=>{data.publication='Cần chỉnh sửa';audit('Kenji yêu cầu chỉnh sửa publication synthetic PUB-013.');notice('Đã yêu cầu chỉnh sửa giả.');},
      'pub-approve':()=>{data.publication='Đã duyệt synthetic';audit('Kenji duyệt publication synthetic PUB-013.');notice('Đã duyệt giả; không upload hoặc phát hành object.');},
      'pub-revoke':()=>{data.publication='Đã thu hồi synthetic';audit('Kenji thu hồi publication synthetic PUB-013.');notice('Đã thu hồi giả; không xóa Storage object.');},
      'deletion-preview':()=>{audit('Đã mở affected-record preview của DEL-004 trong demo.');notice('Preview: 1 raw intake giả → 1 publication metadata giả. Object phải trước metadata.');},
      'deletion-confirm':()=>{data.deletion='FAIL-CLOSED — không xóa thật';audit('DEL-004 được xác nhận trong demo nhưng bị fail-closed an toàn.');notice('FAIL-CLOSED: không có Storage delete, SQL delete hoặc network request.');},
      'deletion-retry':()=>{data.deletion='Retry ghi nhận — vẫn fail-closed';audit('Đã thử lại DEL-004 trong demo; hard gate vẫn đóng.');notice('Retry synthetic đã được ghi; deletion_workflow_ready vẫn false.');}
      ,'ebook-journey':()=>{data.leads+=1;audit('Lead synthetic đi qua ebook journey; không email nào được gửi.');notice('Journey ebook giả: visitor → email → reading access → delivery → nurture theo consent.');}
      ,'assessment-email':()=>{data.assessment.stage='Email entered';notice('Đã nhập email giả; chưa có result.');}
      ,'assessment-answers':()=>{data.assessment.stage='Questions answered';notice('Đã trả lời 6 câu giả; kết quả vẫn khóa trước payment.');}
      ,'assessment-request-payment':()=>{data.assessment.stage='Result locked';notice('Đã yêu cầu payment 50.000 VND giả; report không phải confirmation.');}
      ,'assessment-report-transfer':()=>{data.assessment.stage='Transfer reported';notice('Đã báo chuyển khoản giả; Founder vẫn phải xác nhận.');}
      ,'assessment-confirm-payment':()=>{data.assessment.stage='Payment confirmed';data.assessment.paid=true;notice('Founder đã xác nhận payment giả; giờ mới được tạo result.');}
      ,'assessment-generate':()=>{data.assessment.stage='Result delivered';data.assessment.result='Nhìn rõ bước tiếp theo · rule v0';data.assessment.sequence='Assessment result marked sent (giả) → nurture bắt đầu';audit('Assessment synthetic dùng deterministic rule v0 và đánh dấu result email giả là sent.');notice('Đã tạo kết quả deterministic và đánh dấu email giả là sent.');}
      ,'wizard-back':()=>{data.wizard.step=Math.max(1,data.wizard.step-1);data.wizard.saved=false;}
      ,'wizard-next':()=>{if(data.wizard.start===null){notice('Chọn một cách bắt đầu trước.');return;}data.wizard.step=Math.min(13,data.wizard.step+1);data.wizard.saved=false;}
      ,'wizard-save':()=>{if(data.wizard.start===null){notice('Chọn một cách bắt đầu trước.');return;}data.wizard.saved=true;audit('Đã lưu một product draft synthetic trong localStorage; không tạo route, API hoặc public offer.');notice('Đã lưu bản nháp local. Không có sản phẩm thật được tạo hoặc kích hoạt.');}
      ,'chapter-prev':()=>{const item=libraryItem(data.library.item);data.library.chapter=Math.max(1,data.library.chapter-1);notice(`Đang xem chương ${data.library.chapter}/${item.chapters.length} trong demo.`);}
      ,'chapter-next':()=>{const item=libraryItem(data.library.item);data.library.chapter=Math.min(item.chapters.length,data.library.chapter+1);notice(`Đang xem chương ${data.library.chapter}/${item.chapters.length} trong demo.`);}
      ,'simulate-pdf':()=>{const item=libraryItem(data.library.item);audit(`Đã mô phỏng kiểm tra entitlement và PDF A5 download cho ${item.id}; không có signed URL hay file thật.`);notice('Mô phỏng download: quyền truy cập được kiểm tra, nhưng không có PDF hay URL thật.');}
      ,'support-request':()=>{const item=libraryItem(data.library.item);data.library.supportRequests+=1;audit(`Đã ghi yêu cầu hỗ trợ synthetic cho ${item.id}; không gửi email hay nội dung ấn phẩm.`);notice('Đã ghi yêu cầu hỗ trợ giả. Không có email hoặc ticket thật được tạo.');}
      ,'simulate-revision':()=>{data.library.revisionApplied=true;audit('Đã mô phỏng publication version v3 từ revision được duyệt; version cũ vẫn chỉ lưu nội bộ trong demo.');notice('Đã mô phỏng version mới; customer sẽ mặc định thấy bản hiện tại.');}
    };
    if (publicReading.handleAction(id)) { save(); render(); return; }
    if (customerExperience.handleAction(id)) { save(); render(); return; }
    if (id.startsWith('open-room-')) { data.library.item=id.slice('open-room-'.length);data.library.chapter=1;save();go('reading-room');return; }
    if (id.startsWith('chapter-') && id !== 'chapter-prev' && id !== 'chapter-next') { const pieces=id.split('-');data.library.item=pieces.slice(1,-1).join('-');data.library.chapter=Number(pieces.at(-1));save();render();return; }
    if (id.startsWith('wizard-start-')) { data.wizard.start=Number(id.slice(-1));data.wizard.step=1;data.wizard.saved=false;notice('Đã chọn cách khởi tạo cho bản nháp local.');save();render();return; }
    if (updates[id]) { updates[id](); save(); render(); }
  }
  document.addEventListener('click', event => { const target = event.target.closest('[data-view],[data-action]'); if(!target)return; if(target.dataset.view)go(target.dataset.view); if(target.dataset.action)handleAction(target.dataset.action); });
  document.addEventListener('submit', event => { if(event.target.id === 'ebook-form'){event.preventDefault();const fd=new FormData(event.target);data.ebook.name=String(fd.get('name')).trim()||data.ebook.name;data.ebook.route=String(fd.get('route')).trim()||data.ebook.route;data.ebook.status=String(fd.get('status'));audit('Đã lưu cấu hình ebook synthetic; không tạo route hoặc delivery thật.');save();notice('Đã lưu cấu hình ebook demo.');render();return;} if(event.target.id !== 'settings-form')return; event.preventDefault(); const fd = new FormData(event.target); const next = Object.fromEntries(['price','capacity','delivery','revision','retention'].map(k=>[k,Number(fd.get(k))])); if(next.price < 100000 || next.capacity < 1 || next.capacity > 50 || next.delivery < 1 || next.revision < 1 || next.retention < 1){notice('Không thể lưu: kiểm tra lại range của cài đặt demo.');return;} data.settings=next; const number=Math.max(...data.versions.map(v=>v.number))+1; data.versions.unshift({number,time:now,label:'Phiên bản đang dùng',price:next.price,capacity:next.capacity});data.versions.forEach((v,i)=>{if(i>0)v.label='Lịch sử';});audit(`Đã lưu phiên bản cài đặt demo v${number}; snapshot cũ không thay đổi.`);save();notice(`Đã lưu phiên bản demo v${number}. HM-018 vẫn giữ snapshot v3.`);render(); });
  document.getElementById('reset-demo').addEventListener('click',()=>{data=clone(initial);save();render();notice('Đã đặt lại toàn bộ dữ liệu demo trong trình duyệt này.');});
  document.getElementById('mobile-menu').addEventListener('click',event=>{const side=document.getElementById('sidebar');const open=side.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open));event.currentTarget.textContent=open?'Đóng menu':'Mở menu';});
  const fixtures = [
    { text:'L-024 · hồ sơ Lặng · chờ Kenji quyết định', view:'lang-detail' },
    { text:'L-023 · hồ sơ Lặng · đang đọc', view:'lang' },
    { text:'HM-018 · Hạt Mầm · thanh toán chờ xác nhận', view:'payments' },
    { text:'HM-013 · ấn phẩm · chờ Kenji duyệt', view:'publication' },
    { text:'HM-011 · Hạt Mầm · quá hạn', view:'hatmam' },
    { text:'DEL-004 · deletion preview · fail-closed', view:'deletion' },
    { text:'Tôi đang ở đâu? · assessment 50.000 VND', view:'assessment' },
    { text:'Bạn Là Duy Nhất · preview', view:'adult-publications' },
    { text:'Bản Sắc Giao Mùa · autonomy boundary', view:'child-preview' },
    { text:'Sản phẩm & workflow library', view:'catalog' }
  ];
  searchInput.addEventListener('input', event=>{const query=event.target.value.trim().toLowerCase();if(!query){searchResults.innerHTML='';return;}const matches=fixtures.filter(item=>item.text.toLowerCase().includes(query)).slice(0,5);searchResults.innerHTML=matches.length?matches.map(item=>`<button class="search-result" data-view="${item.view}">${item.text}</button>`).join(''):'<div class="search-result">Không tìm thấy trong dữ liệu giả.</div>';});
  const hash = location.hash.slice(1); if(renderers[hash]) data.view=hash; render();
})();
