/* Public Reading module: an anonymous, same-device synthetic experience only. */
(function () {
  'use strict';
  const chapters = [
    ['Một khoảng để bắt đầu','Không phải mọi điều cần được giải quyết ngay. Có những lúc, chỉ cần ngồi lại với một điều đang mơ hồ đã là một bước đủ thật.'],
    ['Điều đang hiện ra','Khi tiếng ồn dịu xuống, ta thường nhận ra điều mình đã biết từ lâu nhưng chưa kịp gọi tên.'],
    ['Đi qua một nhịp quá nhanh','Không có cách đọc nào đúng cho tất cả mọi người. Có thể dừng ở một câu, rồi quay lại vào một ngày khác.'],
    ['Một điều muốn giữ lại','Có những điều không cần thành kế hoạch. Chỉ cần được đặt ở một nơi đủ yên để không mất đi.'],
    ['Trở về với một điểm bắt đầu','Điều bạn vừa đọc không yêu cầu một quyết định. Nó chỉ có thể mở ra một khoảng nhìn khác cho lần trở lại sau.']
  ];
  function state(data) {
    if (!data.publicReading) data.publicReading={chapter:1,saved:[],invite:false,subscriber:false,preferences:false,returning:false,shared:null,assessment:false};
    return data.publicReading;
  }
  function shell(title, lede, body) { return `<section class="public-reading-shell"><p class="public-kicker">ESSENCE · GÓC ĐỌC CÔNG KHAI · MÔ PHỎNG</p><h1 class="public-title">${title}</h1><p class="public-lede">${lede}</p>${body}</section>`; }
  window.EssencePublicReading = function createPublicReading(ctx) {
    const data=()=>ctx.getData(); const reading=()=>state(data());
    function emailInvite() { const s=reading(); if(!s.invite)return ''; return `<section class="reader-invite" aria-label="Đề xuất email mô phỏng"><p class="public-kicker">EXPERIENCE PROPOSAL · KHÔNG CẦN ĐĂNG KÝ ĐỂ ĐỌC</p><h2>Giữ lại chỗ bạn đang đọc</h2><p>Để tiếp tục đúng phần này trên thiết bị khác, lưu những chương muốn quay lại và nhận bài viết mới khi chúng được mở.</p><p class="small"><strong>Đề xuất consent tương lai:</strong> “Gửi đường dẫn và giữ chỗ đọc” là reading continuity; “Nhận bài viết và thư ESSENCE” là tùy chọn riêng, không là điều kiện để lưu tiến độ.</p><p class="small">Bạn vẫn có thể tiếp tục đọc miễn phí mà không cần đăng ký. Demo chỉ dùng identity cố định <code>READER-DEMO-01</code>; không nhận hay lưu email thật.</p><div class="button-set">${s.subscriber?`${ctx.action(s.preferences?'Đã xem tùy chọn nội dung':'Xem tùy chọn nội dung (mô phỏng)','pr-preferences')} ${ctx.action('Mô phỏng hủy đăng ký','pr-unsubscribe')}`:`${ctx.action('Giữ lại chỗ đang đọc (mô phỏng)','pr-subscribe')} ${ctx.action('Gửi đường dẫn cho tôi (mô phỏng)','pr-subscribe')}`} ${ctx.action('Đóng và tiếp tục đọc','pr-close-invite')}</div></section>`; }
    function comparison() { return `<section class="reader-comparison"><p class="public-kicker">FOUNDER REVIEW · BA TRẠNG THÁI KHÁC NHAU</p><div class="reader-three"><article><h2>Người đọc ẩn danh</h2><p>Đọc trọn ebook, link chương công khai, chia sẻ và tiến độ trên chính thiết bị này. Không email bắt buộc.</p></article><article><h2>Subscriber · tương lai</h2><p>Tiến độ qua thiết bị, chương đã lưu, return link, preferences, bài viết mới và unsubscribe. Không tự thành khách trả phí.</p></article><article><h2>Khách hàng trả phí</h2><p>Không gian riêng, kết quả/ấn phẩm đã mua, Reading Room, PDF khi được duyệt, support và update.</p></article></div></section>`; }
    function renderReader() {
      const s=reading(); const index=Math.min(Math.max(1,s.chapter),chapters.length)-1; const current=chapters[index]; const saved=s.saved.includes(index+1); const end=index===chapters.length-1;
      return shell('Một góc để đọc chậm hơn', 'Một ebook đọc trọn vẹn trên web — công khai, không cần email, tài khoản, thanh toán hay tải PDF.', `
        <section class="reader-cover"><p class="public-kicker">EBOOK CÔNG KHAI · 5 PHẦN · ĐỌC KHOẢNG 12 PHÚT</p><h2>Một khoảng để trở về với điều đang diễn ra</h2><p>${s.returning?'Chào mừng bạn quay lại. Chỗ đọc trên thiết bị này vẫn được giữ trong demo.':'Bạn có thể mở bất kỳ phần nào, hoặc đi lần lượt theo nhịp của mình.'}</p><p class="small">Tiến độ chỉ ở browser/thiết bị này; xóa dữ liệu trình duyệt hoặc đổi thiết bị sẽ không giữ lại tiến độ khi chưa có reader identity đã xác minh.</p><div class="button-set">${ctx.action(s.returning?'Tiếp tục phần đang đọc':'Bắt đầu đọc','pr-resume')} ${ctx.action('Mô phỏng lần quay lại','pr-return')} ${ctx.action('Chia sẻ ebook (mô phỏng)','pr-share-book')}</div></section>
        <section class="reader-layout"><aside class="reader-toc"><p class="public-kicker">MỤC LỤC</p>${chapters.map((chapter,i)=>`<button class="reader-chapter ${index===i?'current':''}" data-action="pr-chapter-${i+1}">${i+1}. ${chapter[0]}</button>`).join('')}</aside><article class="reader-body"><p class="public-kicker">PHẦN ${index+1}/${chapters.length} · KHOẢNG 2–3 PHÚT</p><h2>${current[0]}</h2><p>${current[1]}</p><p>Đây là nội dung mẫu cho Founder review trải nghiệm public reading. Không có asset tải xuống, email gate hay nội dung cá nhân.</p><blockquote>“Có thể chậm lại một chút, để nghe rõ hơn điều đang ở đó.”</blockquote><div class="button-set">${index>0?ctx.action('Phần trước','pr-prev'):''}${index<chapters.length-1?ctx.action('Phần tiếp theo','pr-next'):''} ${ctx.action(saved?'Đã lưu chương này':'Lưu để đọc lại','pr-save')} ${ctx.action('Chia sẻ phần này (mô phỏng)','pr-share-chapter')}</div></article></section>
        ${index===1?`<section class="reader-quiet-cta"><p>Đọc có thể giúp mình nhận ra một điều.</p><p>Một vài câu hỏi có thể giúp mình nhìn rõ hơn nơi đang đứng.</p>${ctx.action('Khám phá bộ câu hỏi','pr-assessment')}</section>`:''}
        ${end?`<section class="reader-end"><p class="public-kicker">MỘT ĐIỂM TRỞ VỀ</p><h2>Có thể bạn đã nhìn thấy một vài điều quen thuộc.</h2><p>Bộ câu hỏi này giúp gom lại những tín hiệu ấy thành một điểm bắt đầu rõ hơn.</p>${ctx.action('Bắt đầu “Tôi đang ở đâu?” — 50.000đ','pr-assessment')} ${ctx.action('Giữ lại chỗ đang đọc','pr-open-invite')}</section>`:''}
        ${emailInvite()}${comparison()}<section class="reader-related"><p class="public-kicker">ĐỌC THÊM · CÁNH CỬA TIẾP THEO</p><h2>Một bài viết liên quan · mô phỏng</h2><p>Một đường link công khai khác sẽ chỉ mở khi có bài đã được Founder duyệt.</p><p class="small">Nếu muốn nhìn rõ hơn nơi mình đang đứng, bạn có thể xem bộ câu hỏi “Tôi đang ở đâu?” — một bước sâu hơn, không phải bắt buộc.</p><div class="button-set">${ctx.action('Sao chép link công khai ổn định (mô phỏng)','pr-copy-link')} ${ctx.action('Khám phá bộ câu hỏi','pr-assessment')}</div></section>
        <div class="button-set">${ctx.action('Quay lại Founder Operating Console','pr-console')} ${ctx.action('Xem Không gian của tôi (paid demo)','pr-customer-space')}</div>`);
    }
    function renderAssessment() {
      return shell('Tôi đang ở đâu?', 'Một bước sâu hơn tùy chọn, đặt sau việc đọc — không phải chẩn đoán, không phải checkout và không có payment trong demo.', `<section class="reader-cover"><p class="public-kicker">ASSESSMENT PREVIEW · 50.000 VND · EXPERIENCE PROPOSAL</p><h2>Một vài câu hỏi để nhìn rõ nơi đang đứng</h2><p>Trong flow thật tương lai: email → câu hỏi phiên bản → kết quả khóa → payment instruction → báo chuyển khoản → Founder xác nhận receipt → result deterministic → private entitlement.</p><p class="small">Không có form, email, payment, AI scoring hay kết quả thật trong WP2.</p><div class="button-set">${ctx.action('Quay lại Góc đọc','pr-reader')} ${ctx.action('Xem paid Customer Space demo','pr-customer-space')}</div></section>`);
    }
    function renderLaunchCore() {
      return ctx.page('Launch Core · Founder priority lock', 'Chỉ ba capability liên kết là ưu tiên backend tiếp theo. Tất cả provider và activation vẫn OFF.', `<div class="notice"><strong>Immediate, not active.</strong> Đây là bản đồ Founder review — không đóng gate nào và không bắt đầu WP3.</div><section class="grid three"><article class="card"><p class="section-label">CORE 1</p><h2>Lặng backend</h2><p class="small">Intake → support summary → Kenji decision → payment evidence → payment confirmation → booking → follow-up. Không AI suitability, không checkout/booking trước payment.</p></article><article class="card"><p class="section-label">CORE 2</p><h2>Hạt Mầm backend</h2><p class="small">Consent → HM-01/HM-02 snapshot → evidence → production/review/revision → version → private delivery/PDF/support/retention/deletion. Không legacy KIDMAP.</p></article><article class="card"><p class="section-label">CORE 3</p><h2>Private Reading Room</h2><p class="small">Verified identity, magic link, entitlement isolation, Storage, signed download, versioning, support/revoke/deletion/audit và mobile reading.</p></article></section><section class="grid two" style="margin-top:14px"><article class="card"><h2>Growth next · deferred</h2><p class="small">Public ebook real route, subscriber identity/cross-device progress, reading email, assessment backend và baseline CRM.</p></article><article class="card"><h2>Expansion later · deferred</h2><p class="small">Adult preview products, Khám Phá, Giao Mùa, membership, Journey backend, advanced CRM/AI/media.</p></article></section><section class="card" style="margin-top:14px"><h2>Provider readiness</h2><p>${ctx.badge('SUPABASE / AUTH / STORAGE / EMAIL / PAYMENT / CAL.COM — OFF','blocked')}</p></section><div class="button-set">${ctx.action('Quay lại Console','pr-console')} ${ctx.action('Mở Góc đọc công khai','pr-reader')}</div>`);
    }
    function handleAction(id) {
      const s=reading();
      if(id==='pr-reader'){data().view='public-reading';return true;} if(id==='pr-console'){data().view='overview';return true;} if(id==='pr-customer-space'){data().view='customer-home';return true;} if(id==='pr-assessment'){data().view='assessment-landing';return true;}
      if(id==='pr-resume'||id==='pr-return'){s.returning=true;ctx.notice('Đã mô phỏng quay lại trên cùng thiết bị.');return true;} if(id==='pr-prev'){s.chapter=Math.max(1,s.chapter-1);s.returning=true;return true;} if(id==='pr-next'){s.chapter=Math.min(chapters.length,s.chapter+1);s.returning=true;return true;}
      if(id==='pr-save'){const current=s.chapter;s.saved=s.saved.includes(current)?s.saved.filter(v=>v!==current):[...s.saved,current];if(s.saved.includes(current)){s.invite=true;ctx.notice('Đã lưu chương giả trên thiết bị này. Có thể xem đề xuất email tùy chọn.');}else{ctx.notice('Đã bỏ lưu chương giả.');}return true;}
      if(id==='pr-open-invite'){s.invite=true;return true;} if(id==='pr-close-invite'){s.invite=false;ctx.notice('Đã đóng đề xuất. Bạn vẫn đọc miễn phí.');return true;} if(id==='pr-subscribe'){s.subscriber=true;ctx.audit('Reader demo READER-DEMO-01 chọn lưu chỗ đọc; không tạo email, consent hay subscriber thật.');ctx.notice('Mô phỏng subscriber: chỉ localStorage, không gửi email.');return true;} if(id==='pr-preferences'){s.preferences=true;ctx.notice('Đã mô phỏng xem tùy chọn nội dung; chưa tạo consent record.');return true;} if(id==='pr-unsubscribe'){s.subscriber=false;s.preferences=false;ctx.audit('Reader demo READER-DEMO-01 mô phỏng unsubscribe; không có email thật.');ctx.notice('Đã mô phỏng hủy nhận nội dung.');return true;}
      if(id==='pr-share-book'||id==='pr-share-chapter'||id==='pr-copy-link'){s.shared=id;ctx.notice(id==='pr-share-chapter'?'Đã mô phỏng chia sẻ link phần đang đọc.':'Đã mô phỏng sao chép/chia sẻ link công khai.');return true;}
      if(id.startsWith('pr-chapter-')){s.chapter=Number(id.slice('pr-chapter-'.length));s.returning=true;return true;}
      return false;
    }
    return {renderReader,renderAssessment,renderLaunchCore,handleAction};
  };
})();
