#!/usr/bin/env bash
# Isolated B9 restore drill. This script never connects to Supabase, staging,
# or production. It verifies the B8 snapshot, restores it into a disposable
# local PostgreSQL container, prints metadata/counts only, then destroys every
# Docker resource it created.
set -Eeuo pipefail

readonly SCHEMA_DUMP='/Users/macos/Documents/03. RESOURCES/coachkenjipham-backups/essence-staging/2026-08-03-pre-0017-b8/essence-staging-pre-0017-schema.sql'
readonly DATA_DUMP='/Users/macos/Documents/03. RESOURCES/coachkenjipham-backups/essence-staging/2026-08-03-pre-0017-b8/essence-staging-pre-0017-data.sql'
readonly SCHEMA_SHA='a93145f2ddc69a3f1be222b57cff084bade6ae60f318242a0058f070d950c76e'
readonly DATA_SHA='6af4b50a42fb448b538ba93d56714fa10fe561a60b309427c126e9aef78f9ae0'
readonly RUN_ID="essence-restore-audit-$(date +%s)-$$"
readonly CONTAINER="$RUN_ID"
readonly NETWORK="$RUN_ID-net"
readonly VOLUME="$RUN_ID-data"
readonly STARTED_AT="$(date +%s)"

cleanup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  docker network rm "$NETWORK" >/dev/null 2>&1 || true
  docker volume rm "$VOLUME" >/dev/null 2>&1 || true
}
trap cleanup EXIT

actual_schema_sha="$(shasum -a 256 "$SCHEMA_DUMP" | awk '{print $1}')"
actual_data_sha="$(shasum -a 256 "$DATA_DUMP" | awk '{print $1}')"
[[ "$actual_schema_sha" == "$SCHEMA_SHA" ]] || { echo 'RESTORE_DRILL=FAILED_SCHEMA_CHECKSUM'; exit 1; }
[[ "$actual_data_sha" == "$DATA_SHA" ]] || { echo 'RESTORE_DRILL=FAILED_DATA_CHECKSUM'; exit 1; }
echo 'CHECKSUMS=PASS'

docker network create --internal "$NETWORK" >/dev/null
docker volume create "$VOLUME" >/dev/null
docker run -d --name "$CONTAINER" --network "$NETWORK" \
  --mount "type=volume,src=$VOLUME,dst=/var/lib/postgresql/data" \
  -e POSTGRES_HOST_AUTH_METHOD=trust postgres:16-alpine >/dev/null

for attempt in $(seq 1 30); do
  if docker exec "$CONTAINER" pg_isready -U postgres -d postgres >/dev/null 2>&1; then break; fi
  if [[ "$attempt" == 30 ]]; then echo 'RESTORE_DRILL=FAILED_POSTGRES_START'; exit 1; fi
  sleep 1
done

# The staging dump contains public-schema objects only. These local shims make
# policy/function dependencies resolvable without claiming that Auth, Storage,
# Realtime, or Supabase migration metadata were restored.
docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d postgres >/dev/null <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN CREATE ROLE anon NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN CREATE ROLE service_role NOLOGIN; END IF;
END $$;
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS app_private;
CREATE TABLE IF NOT EXISTS auth.users (id uuid PRIMARY KEY);
CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb
  LANGUAGE sql STABLE AS $$
    SELECT COALESCE(NULLIF(current_setting('request.jwt.claims', true), ''), '{}')::jsonb
  $$;
CREATE OR REPLACE FUNCTION app_private.is_admin() RETURNS boolean
  LANGUAGE sql STABLE AS $$
    SELECT COALESCE((auth.jwt() ->> 'is_admin')::boolean, false)
  $$;
GRANT USAGE ON SCHEMA auth, app_private TO authenticated;
GRANT EXECUTE ON FUNCTION auth.jwt(), app_private.is_admin() TO authenticated;
SQL

docker cp "$SCHEMA_DUMP" "$CONTAINER:/tmp/schema.sql"
docker cp "$DATA_DUMP" "$CONTAINER:/tmp/data.sql"
docker exec "$CONTAINER" psql -v ON_ERROR_STOP=1 -q -U postgres -d postgres -f /tmp/schema.sql
# The public-only snapshot intentionally excludes auth.users. Temporarily
# disable this one external FK while seed rows load; recreate matching local
# Auth stubs immediately before reenabling it, so the local restore is
# referentially consistent without importing Auth identities or credentials.
docker exec "$CONTAINER" psql -v ON_ERROR_STOP=1 -q -U postgres -d postgres -c 'ALTER TABLE public.admin_users DISABLE TRIGGER ALL'
# The dump was generated by a newer managed PostgreSQL version. PostgreSQL 16
# does not know transaction_timeout; remove only that session-setting line,
# never SQL/data rows, for the local compatibility target.
docker exec "$CONTAINER" sh -c "sed '/^SET transaction_timeout/d' /tmp/data.sql > /tmp/data-compat.sql"
docker exec "$CONTAINER" psql -v ON_ERROR_STOP=1 -q -U postgres -d postgres -f /tmp/data-compat.sql
docker exec "$CONTAINER" psql -v ON_ERROR_STOP=1 -q -U postgres -d postgres -c 'INSERT INTO auth.users (id) SELECT user_id FROM public.admin_users ON CONFLICT DO NOTHING'
docker exec "$CONTAINER" psql -v ON_ERROR_STOP=1 -q -U postgres -d postgres -c 'ALTER TABLE public.admin_users ENABLE TRIGGER ALL'

echo 'RESTORE_SCHEMA_AND_SEED_DATA=PASS'
docker exec -i "$CONTAINER" psql -X -A -F '|' -v ON_ERROR_STOP=1 -U postgres -d postgres <<'SQL'
SELECT 'PUBLIC_TABLES=' || count(*) FROM pg_tables WHERE schemaname = 'public';
SELECT 'PUBLIC_FUNCTIONS=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public';
SELECT 'RLS_ENABLED_TABLES=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity;
SELECT 'POLICIES=' || count(*) FROM pg_policies WHERE schemaname = 'public';
SELECT 'SEED_ROW_COUNTS=' || string_agg(tablename || ':' || rows, ',' ORDER BY tablename) FROM (
  SELECT 'admin_users' AS tablename, count(*)::text AS rows FROM public.admin_users
  UNION ALL SELECT 'hatmam_orders', count(*)::text FROM public.hatmam_orders
  UNION ALL SELECT 'hatmam_child_profiles', count(*)::text FROM public.hatmam_child_profiles
  UNION ALL SELECT 'lang_applications', count(*)::text FROM public.lang_applications
  UNION ALL SELECT 'payments', count(*)::text FROM public.payments
  UNION ALL SELECT 'publications', count(*)::text FROM public.publications
) safe_counts;
SELECT 'SUPABASE_MIGRATION_HISTORY_IN_SNAPSHOT=' || CASE WHEN to_regclass('supabase_migrations.schema_migrations') IS NULL THEN 'NOT_INCLUDED_PUBLIC_SCHEMA_DUMP' ELSE 'PRESENT' END;
SET ROLE anon;
SELECT 'ANON_CHILD_SELECT_PRIVILEGE=' || has_table_privilege('anon', 'public.hatmam_child_profiles', 'select');
RESET ROLE;
SET ROLE authenticated;
SELECT set_config('request.jwt.claims', '{"aal":"aal1","is_admin":true}', false);
SELECT 'AAL1_ADMIN_CHILD_VISIBLE_ROWS=' || count(*) FROM public.hatmam_child_profiles;
SELECT set_config('request.jwt.claims', '{"aal":"aal2","is_admin":false}', false);
SELECT 'AAL2_NON_ADMIN_CHILD_VISIBLE_ROWS=' || count(*) FROM public.hatmam_child_profiles;
SELECT set_config('request.jwt.claims', '{"aal":"aal2","is_admin":true}', false);
SELECT 'AAL2_ADMIN_CHILD_VISIBLE_ROWS=' || count(*) FROM public.hatmam_child_profiles;
RESET ROLE;
SELECT 'RATE_LIMIT_FIRST=' || public.consume_rate_limit(repeat('a', 64), 1, 60);
SELECT 'RATE_LIMIT_SECOND=' || public.consume_rate_limit(repeat('a', 64), 1, 60);
SQL

echo "DURATION_SECONDS=$(( $(date +%s) - STARTED_AT ))"
echo 'RESTORE_DRILL=PASS_PUBLIC_SCHEMA_AND_SEED_DATA_WITH_LOCAL_SUPABASE_SHIMS'
